export const FETCH_ONE_USER = "USER/FETCH_ONE_USER";
export const FETCH_ONE_USER_STARTED = "USER/FETCH_ONE_USER_STARTED";
export const FETCH_ONE_USER_SUCCESS = "USER/FETCH_ONE_USER_SUCCESS";
export const FETCH_ONE_USER_FAILED = "USER/FETCH_ONE_USER_FAILED";

export const FETCH_MANY_USERS = "USER/FETCH_MANY_USERS";
export const FETCH_MANY_USERS_STARTED = "USER/FETCH_MANY_USERS_STARTED";
export const FETCH_MANY_USERS_SUCCESS = "USER/FETCH_MANY_USERS_SUCCESS";
export const FETCH_MANY_USERS_FAILED = "USER/FETCH_MANY_USERS_FAILED";

export const SHOW_USER = "USER/SHOW_USER";
export const SHOW_USER_STARTED = "USER/SHOW_USER_STARTED";
export const SHOW_USER_SUCCESS = "USER/SHOW_USER_SUCCESS";
export const SHOW_USER_FAILED = "USER/SHOW_USER_FAILED";

export const CREATE_USER = "USER/CREATE_USER";
export const CREATE_USER_STARTED = "USER/CREATE_USER_STARTED";
export const CREATE_USER_SUCCESS = "USER/CREATE_USER_SUCCESS";
export const CREATE_USER_FAILED = "USER/CREATE_USER_FAILED";

export const UPDATE_USER = "USER/UPDATE_USER";
export const UPDATE_USER_STARTED = "USER/UPDATE_USER_STARTED";
export const UPDATE_USER_SUCCESS = "USER/UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "USER/UPDATE_USER_FAILED";

export const DELETE_USER = "USER/DELETE_USER";
export const DELETE_USER_STARTED = "USER/DELETE_USER_STARTED";
export const DELETE_USER_SUCCESS = "USER/DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "USER/DELETE_USER_FAILED";
