export const FETCH_MANY_CATEGORIES = "CATEGORY/FETCH_MANY_CATEGORIES";
export const FETCH_MANY_CATEGORIES_STARTED =
  "CATEGORY/FETCH_MANY_CATEGORIES_STARTED";
export const FETCH_MANY_CATEGORIES_SUCCESS =
  "CATEGORY/FETCH_MANY_CATEGORIES_SUCCESS";
export const FETCH_MANY_CATEGORIES_FAILED =
  "CATEGORY/FETCH_MANY_CATEGORIES_FAILED";

export const FETCH_ONE_CATEGORY = "CATEGORY/FETCH_ONE_CATEGORY";
export const FETCH_ONE_CATEGORY_STARTED = "CATEGORY/FETCH_ONE_CATEGORY_STARTED";
export const FETCH_ONE_CATEGORY_SUCCESS = "CATEGORY/FETCH_ONE_CATEGORY_SUCCESS";
export const FETCH_ONE_CATEGORY_FAILED = "CATEGORY/FETCH_ONE_CATEGORY_FAILED";

export const SHOW_CATEGORY = "CATEGORY/SHOW_CATEGORY";
export const SHOW_CATEGORY_STARTED = "CATEGORY/SHOW_CATEGORY_STARTED";
export const SHOW_CATEGORY_SUCCESS = "CATEGORY/SHOW_CATEGORY_SUCCESS";
export const SHOW_CATEGORY_FAILED = "CATEGORY/SHOW_CATEGORY_FAILED";

export const CREATE_CATEGORY = "CATEGORY/CREATE_CATEGORY";
export const CREATE_CATEGORY_STARTED = "CATEGORY/CREATE_CATEGORY_STARTED";
export const CREATE_CATEGORY_SUCCESS = "CATEGORY/CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILED = "CATEGORY/CREATE_CATEGORY_FAILED";

export const UPDATE_CATEGORY = "CATEGORY/UPDATE_CATEGORY";
export const UPDATE_CATEGORY_STARTED = "CATEGORY/UPDATE_CATEGORY_STARTED";
export const UPDATE_CATEGORY_SUCCESS = "CATEGORY/UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILED = "CATEGORY/UPDATE_CATEGORY_FAILED";

export const DELETE_CATEGORY = "CATEGORY/DELETE_CATEGORY";
export const DELETE_CATEGORY_STARTED = "CATEGORY/DELETE_CATEGORY_STARTED";
export const DELETE_CATEGORY_SUCCESS = "CATEGORY/DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILED = "CATEGORY/DELETE_CATEGORY_FAILED";
