export const FETCH_ONE_PRODUCT = "PRODUCT/FETCH_ONE_PRODUCT";
export const FETCH_ONE_PRODUCT_STARTED = "PRODUCT/FETCH_ONE_PRODUCT_STARTED";
export const FETCH_ONE_PRODUCT_SUCCESS = "PRODUCT/FETCH_ONE_PRODUCT_SUCCESS";
export const FETCH_ONE_PRODUCT_FAILED = "PRODUCT/FETCH_ONE_PRODUCT_FAILED";

export const FETCH_MANY_PRODUCTS = "PRODUCT/FETCH_MANY_PRODUCTS";
export const FETCH_MANY_PRODUCTS_STARTED = "PRODUCT/FETCH_MANY_PRODUCTS_STARTED";
export const FETCH_MANY_PRODUCTS_SUCCESS = "PRODUCT/FETCH_MANY_PRODUCTS_SUCCESS";
export const FETCH_MANY_PRODUCTS_FAILED = "PRODUCT/FETCH_MANY_PRODUCTS_FAILED";

export const SHOW_PRODUCT = "PRODUCT/SHOW_PRODUCT";
export const SHOW_PRODUCT_STARTED = "PRODUCT/SHOW_PRODUCT_STARTED";
export const SHOW_PRODUCT_SUCCESS = "PRODUCT/SHOW_PRODUCT_SUCCESS";
export const SHOW_PRODUCT_FAILED = "PRODUCT/SHOW_PRODUCT_FAILED";

export const CREATE_PRODUCT = "PRODUCT/CREATE_PRODUCT";
export const CREATE_PRODUCT_STARTED = "PRODUCT/CREATE_PRODUCT_STARTED";
export const CREATE_PRODUCT_SUCCESS = "PRODUCT/CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILED = "PRODUCT/CREATE_PRODUCT_FAILED";

export const UPDATE_PRODUCT = "PRODUCT/UPDATE_PRODUCT";
export const UPDATE_PRODUCT_STARTED = "PRODUCT/UPDATE_PRODUCT_STARTED";
export const UPDATE_PRODUCT_SUCCESS = "PRODUCT/UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILED = "PRODUCT/UPDATE_PRODUCT_FAILED";

export const DELETE_PRODUCT = "PRODUCT/DELETE_PRODUCT";
export const DELETE_PRODUCT_STARTED = "PRODUCT/DELETE_PRODUCT_STARTED";
export const DELETE_PRODUCT_SUCCESS = "PRODUCT/DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED = "PRODUCT/DELETE_PRODUCT_FAILED";
